name: Deploy on DEV
on:
  push:
    branches: ["develop"]
jobs:
  deploy:
    name: Deploy on DEV
    runs-on: ubuntu-latest
    environment: develop
    steps:
    - name: setup
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ vars.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script_stop: true
        script: |
          mkdir deploy-folder
          cd deploy-folder
          git clone git@github.com:MrCrakerz/IdleRacerXtrem.git
          cd IdleRacerXtrem
          git switch develop
    - name: build back
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ vars.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script_stop: true
        script: |
          cd deploy-folder/IdleRacerXtrem/back
          npm install
          npm run build
    - name: build front
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ vars.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script_stop: true
        script: |
          cd deploy-folder/IdleRacerXtrem/front
          npm install
          npm run build
