name: Deploy on DEV

on:
  push:
    branches: ["develop"]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: develop
    steps:
    - name: deploy dev
      uses: garygrossgarten/github-action-ssh@release
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        command: whoami
