# Simple workflow for deploying static content to GitHub Pages
name: Deploy on DEV

on:
  push:
    branches: ["develop"]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Deploy on DEV
        run: |
          ssh {{ secrets.USER }}: {{ secrets.PASSWORD }}@{{ secrets.HOST }}
 
