name: Deploy on DEV
on:
  push:
    branches: ["develop"]
jobs:
  deploy:
    name: Deploy on DEV
    runs-on: ubuntu-latest
    environment: develop
    steps:
    - name: Deploy on DEV
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          git clone git@github.com:MrCrakerz/IdleRacerXtrem.git
          cd IdleRacerXtrem/front
          git switch develop
          npm install
          npm run build
          rm -rf /var/www/html/*
          cp -r dist/* /var/www/html/
          rm -rf /root/IdleRacerXtrem
