name: Deploy on DEV

on:
  push:
    branches: ["develop"]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
        script: whoami
