name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    environment: develop
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          git clone git@github.com:MrCrakerz/IdleRacerXtrem.git
          cd IdleRacerXtrem/front
          npm install
          npm run build
          rm -rf /var/www/html/*
          cp -r dist/* /var/www/html/
          rm -rf /root/IdleRacerXtrem
