# Simple workflow for deploying static content to GitHub Pages
name: Deploy on DEV

on:
  push:
    branches: ["develop"]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Deploy on DEV
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.host}}
          username: ${{secrets.username}}
          password: ${{secrets.password}}
          script: |
            echo "OK"
          
