name: Node CI

on: [push]

jobs:
  build-back:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: npm install, build
        run: |
          cd back
          npm install -g @nestjs/cli
          npm install --omit=dev
          npm run build --if-present
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifact_back
          path: |
              dist
  build-front:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: npm install, build
        run: |
          cd front
          npm install --omit=dev
          npm run build --if-present
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifact_front
          path: |
              dist
  deploy-back:
    runs-on: ubuntu-latest
    needs: build-back
    steps:
    - name: download artifact
      uses: actions/download-artifact@v3
      with:
        name: artifact_back
        path: back
        
    - name: copy file to server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ vars.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        source: back
        target: back
  deploy-front:
    runs-on: ubuntu-latest
    needs: build-front
    steps:
    - name: download artifact
      uses: actions/download-artifact@v3
      with:
        name: artifact_front
        path: front
        
    - name: copy file to server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ vars.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        source: front
        target: front
        
